import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from nukeai import languages as L
from nukeai import planfile
from nukeai.classify import Protections, classify
from nukeai.document import Document, canonical
from nukeai.reducer import Options, plan_nuke, plan_reduce
from nukeai.rewrite import DELETE, REPLACE, Edit, apply_edits, verify_code_unchanged

FIXTURES = Path(__file__).parent / "fixtures"


def prepared(text, path="x.ts", prot=None):
    doc = Document.from_text(text, path)
    classify(doc.comments, prot or Protections())
    return doc


def nuked(text, path="x.ts", prot=None, opts=None):
    doc = prepared(text, path, prot)
    return apply_edits(doc.text, plan_nuke(doc, opts or Options()))


def reduced(text, path="x.ts", prot=None, opts=None):
    doc = prepared(text, path, prot)
    return apply_edits(doc.text, plan_reduce(doc, opts or Options()))


class TestProtections(unittest.TestCase):
    def assert_kept(self, src, needle, path="x.ts"):
        self.assertIn(needle, nuked(src, path))

    def test_eslint_disable(self):
        self.assert_kept("// eslint-disable-next-line no-eval\neval(x);\n",
                         "eslint-disable")

    def test_ts_expect_error(self):
        self.assert_kept("// @ts-expect-error legacy\nf();\n", "@ts-expect-error")

    def test_noqa(self):
        self.assert_kept("import os  # noqa: F401\n", "noqa", "x.py")

    def test_type_ignore(self):
        self.assert_kept("x = f()  # type: ignore[arg-type]\n", "type: ignore", "x.py")

    def test_shebang(self):
        self.assert_kept("#!/usr/bin/env bash\necho 1\n", "#!/usr/bin/env", "x.sh")

    def test_coding_declaration(self):
        self.assert_kept("# -*- coding: utf-8 -*-\nx = 1\n", "coding", "x.py")

    def test_license_header(self):
        self.assert_kept("// Copyright (c) 2024 Acme\nconst a = 1;\n", "Copyright")

    def test_spdx(self):
        self.assert_kept("// SPDX-License-Identifier: MIT\nconst a = 1;\n", "SPDX")

    def test_todo_and_friends(self):
        for marker in ("TODO", "FIXME", "HACK", "XXX", "BUG", "NOTE", "DEPRECATED"):
            with self.subTest(marker=marker):
                self.assert_kept(f"// {marker}: quelque chose\nconst a = 1;\n", marker)

    def test_jsdoc_kept_by_default(self):
        src = "/**\n * Fait un truc.\n */\nfunction f() {}\n"
        self.assertIn("Fait un truc", nuked(src))

    def test_jsdoc_removed_with_include_docstrings(self):
        src = "/**\n * Fait un truc.\n */\nfunction f() {}\n"
        out = nuked(src, prot=Protections(docs=False))
        self.assertNotIn("Fait un truc", out)

    def test_python_docstring_kept_by_default(self):
        src = 'def f():\n    """Doc."""\n    return 1\n'
        self.assertIn("Doc.", nuked(src, "x.py"))

    def test_docstring_that_is_the_whole_body_survives(self):
        src = 'def stub():\n    """Corps unique."""\n'
        out = nuked(src, "x.py", prot=Protections(docs=False))
        self.assertIn("Corps unique", out)
        compile(out, "x.py", "exec")

    def test_docstring_with_a_body_after_it_is_removed(self):
        src = 'def f():\n    """Doc."""\n    return 1\n'
        out = nuked(src, "x.py", prot=Protections(docs=False))
        self.assertNotIn("Doc.", out)
        compile(out, "x.py", "exec")

    def test_module_docstring_alone_is_removable(self):
        src = '"""Doc du module."""\n'
        out = nuked(src, "x.py", prot=Protections(docs=False))
        self.assertNotIn("Doc du module", out)

    def test_go_build_directive(self):
        self.assert_kept("//go:build linux\npackage main\n", "go:build", "x.go")

    def test_shellcheck_directive(self):
        self.assert_kept("# shellcheck disable=SC2086\necho $x\n", "shellcheck", "x.sh")

    def test_do_not_edit_marker(self):
        self.assert_kept("// Code generated by protoc. DO NOT EDIT.\npackage x\n",
                         "DO NOT EDIT", "x.go")


class TestNuke(unittest.TestCase):
    def test_removes_own_line_comment_entirely(self):
        self.assertEqual(nuked("// bruit\nconst a = 1;\n"), "const a = 1;\n")

    def test_removes_trailing_comment_and_whitespace(self):
        self.assertEqual(nuked("const a = 1; // bruit\n"), "const a = 1;\n")

    def test_keeps_code_when_comment_precedes_it_on_the_line(self):
        self.assertEqual(nuked("/* x */ const a = 1;\n"), "const a = 1;\n")

    def test_removes_jsx_braces_with_the_comment(self):
        src = "<div>\n  {/* note */}\n  <b/>\n</div>\n"
        self.assertEqual(nuked(src, "x.tsx"), "<div>\n  <b/>\n</div>\n")

    def test_does_not_leave_a_double_blank_line(self):
        src = "const a = 1;\n\n// bloc\n// suite\n\nconst b = 2;\n"
        self.assertEqual(nuked(src), "const a = 1;\n\nconst b = 2;\n")

    def test_leaves_single_blank_line_untouched(self):
        src = "const a = 1;\n// bloc\nconst b = 2;\n"
        self.assertEqual(nuked(src), "const a = 1;\nconst b = 2;\n")

    def test_string_containing_slashes_is_untouched(self):
        src = 'const u = "http://a//b"; // bruit\n'
        self.assertEqual(nuked(src), 'const u = "http://a//b";\n')

    def test_min_ai_score_filters(self):
        src = "// Initialize the counter to zero\nlet counter = 0;\n// détail métier obscur\nlet x = 1;\n"
        out = nuked(src, opts=Options(min_ai_score=0.5))
        self.assertNotIn("Initialize the counter", out)
        self.assertIn("détail métier obscur", out)


class TestReduce(unittest.TestCase):
    def test_collapses_a_block_to_one_line(self):
        src = ("/* Première phrase courte. Note that ceci est du remplissage "
               "supplémentaire qui ne sert à rien. */\nconst a = 1;\n")
        out = reduced(src)
        self.assertIn("Première phrase courte.", out)
        self.assertNotIn("remplissage", out)

    def test_drops_a_decorative_banner_block(self):
        src = "// =========\n// SECTION\n// =========\nconst a = 1;\n"
        self.assertEqual(reduced(src), "const a = 1;\n")

    def test_drops_a_pure_restatement(self):
        src = "// Increment the counter\ncounter += 1;\n"
        self.assertEqual(reduced(src), "counter += 1;\n")

    def test_keeps_a_comment_that_says_something_new(self):
        src = "// l'ordre compte, la remise passe avant la TVA\ntotal = f(x);\n"
        self.assertIn("la remise passe avant la TVA", reduced(src))

    def test_strips_the_this_function_preamble(self):
        src = "// This function converts the payload\nfunction g() {}\n"
        self.assertIn("// converts the payload", reduced(src))

    def test_respects_max_len(self):
        long = "a " * 120
        src = f"// {long}\nconst a = 1;\n"
        out = reduced(src, opts=Options(max_len=60))
        self.assertTrue(max(len(l) for l in out.splitlines()) <= 62)

    def test_docs_untouched_without_shrink_docs(self):
        src = "/**\n * Résumé.\n * Note that du remplissage.\n */\nfunction f() {}\n"
        self.assertEqual(reduced(src), src)

    def test_docs_shortened_with_shrink_docs(self):
        src = "/**\n * Résumé.\n * Note that du remplissage.\n */\nfunction f() {}\n"
        out = reduced(src, opts=Options(shrink_docs=True))
        self.assertIn("Résumé.", out)
        self.assertNotIn("remplissage", out)

    def test_docs_are_never_deleted_even_with_shrink_docs(self):
        src = "/**\n * Note that du pur remplissage.\n */\nfunction f() {}\n"
        out = reduced(src, opts=Options(shrink_docs=True))
        self.assertIn("/**", out)

    def test_python_docstring_sections_survive(self):
        src = ('def f(path):\n'
               '    """Charge le fichier.\n\n'
               '    Cette fonction lit le JSON et retourne un dict.\n\n'
               '    Args:\n        path: Le chemin\n'
               '    Returns:\n        Le dictionnaire\n'
               '    """\n    return 1\n')
        out = reduced(src, "x.py", opts=Options(shrink_docs=True))
        self.assertIn("Args:", out)
        self.assertIn("path: Le chemin", out)
        self.assertNotIn("Cette fonction lit", out)

    def test_dedupes_repeated_comments(self):
        src = "// même chose\nlet a = 1;\n// même chose\nlet b = 2;\n"
        self.assertEqual(reduced(src).count("même chose"), 1)


class TestRenderRoundTrip(unittest.TestCase):
    def replace(self, src, new_lines, path="x.ts"):
        doc = prepared(src, path)
        classify(doc.comments, Protections(docs=False))
        edit = Edit(doc.comments[0], REPLACE, tuple(new_lines))
        return apply_edits(doc.text, [edit])

    def test_line_comment(self):
        self.assertEqual(self.replace("// long\nconst a = 1;\n", ["court"]),
                         "// court\nconst a = 1;\n")

    def test_indented_line_comment(self):
        self.assertEqual(self.replace("function f() {\n  // long\n}\n", ["court"]),
                         "function f() {\n  // court\n}\n")

    def test_block_to_single_line(self):
        self.assertEqual(self.replace("/* a\n b */\nconst a = 1;\n", ["court"]),
                         "/* court */\nconst a = 1;\n")

    def test_jsdoc_keeps_its_form(self):
        out = self.replace("/**\n * a\n * b\n */\nfunction f() {}\n", ["un", "deux"])
        self.assertEqual(out, "/**\n * un\n * deux\n */\nfunction f() {}\n")

    def test_html_comment(self):
        self.assertEqual(self.replace("<!-- long -->\n<p></p>\n", ["court"], "x.html"),
                         "<!-- court -->\n<p></p>\n")

    def test_python_docstring_single_line(self):
        out = self.replace('def f():\n    """a\n\n    b\n    """\n', ["court"], "x.py")
        self.assertEqual(out, 'def f():\n    """court"""\n')

    def test_multiline_line_comments_keep_indent(self):
        out = self.replace("  // a\nx();\n", ["un", "deux"])
        self.assertEqual(out, "  // un\n  // deux\nx();\n")


class TestInvariantOnFixtures(unittest.TestCase):
    """Le code hors commentaires ne bouge jamais, quel que soit le mode."""

    def each(self):
        for path in sorted(FIXTURES.iterdir()):
            doc = Document.load(path)
            if doc:
                yield path, doc

    def test_nuke_preserves_code(self):
        for path, doc in self.each():
            with self.subTest(fixture=path.name):
                classify(doc.comments, Protections())
                out = apply_edits(doc.text, plan_nuke(doc, Options()))
                ok, why = verify_code_unchanged(doc.text, out, doc.spec)
                self.assertTrue(ok, f"{path.name}: {why}")

    def test_reduce_preserves_code(self):
        for path, doc in self.each():
            with self.subTest(fixture=path.name):
                classify(doc.comments, Protections())
                out = apply_edits(doc.text, plan_reduce(doc, Options(shrink_docs=True)))
                ok, why = verify_code_unchanged(doc.text, out, doc.spec)
                self.assertTrue(ok, f"{path.name}: {why}")

    def test_aggressive_nuke_preserves_code(self):
        prot = Protections(directives=False, headers=False, markers=False, docs=False)
        for path, doc in self.each():
            with self.subTest(fixture=path.name):
                classify(doc.comments, prot)
                out = apply_edits(doc.text, plan_nuke(doc, Options()))
                ok, why = verify_code_unchanged(doc.text, out, doc.spec)
                self.assertTrue(ok, f"{path.name}: {why}")

    def test_nuked_python_still_parses(self):
        path = FIXTURES / "service.py"
        doc = Document.load(path)
        classify(doc.comments, Protections())
        out = apply_edits(doc.text, plan_nuke(doc, Options()))
        compile(out, str(path), "exec")

    def test_protected_comments_survive(self):
        for path, doc in self.each():
            with self.subTest(fixture=path.name):
                classify(doc.comments, Protections())
                out = apply_edits(doc.text, plan_nuke(doc, Options()))
                for c in doc.comments:
                    if c.protected:
                        self.assertIn(c.inner_lines[0][:40].strip(), out,
                                      f"{path.name}: {c.protected} perdu")

    def test_sql_string_inside_python_is_not_touched(self):
        doc = Document.load(FIXTURES / "service.py")
        classify(doc.comments, Protections())
        out = apply_edits(doc.text, plan_nuke(doc, Options()))
        self.assertIn("SELECT *  -- pas un commentaire python", out)

    def test_shell_heredoc_body_survives(self):
        doc = Document.load(FIXTURES / "deploy.sh")
        classify(doc.comments, Protections())
        out = apply_edits(doc.text, plan_nuke(doc, Options()))
        self.assertIn("# ceci n'est pas un commentaire", out)


class TestPlanFile(unittest.TestCase):
    def build(self, src, path, mode="humanize", opts=None):
        tmp = Path(tempfile.mkdtemp())
        f = tmp / path
        f.write_text(src, encoding="utf-8")
        doc = Document.load(f)
        classify(doc.comments, Protections())
        plan = planfile.build([doc], mode, opts or Options(), tmp)
        return tmp, f, plan

    def test_plan_lists_eligible_comments_only(self):
        src = "// eslint-disable-next-line x\n// bruit\nconst a = 1;\n"
        _, _, plan = self.build(src, "a.ts")
        self.assertEqual([i["current"] for i in plan["items"]], [["bruit"]])

    def test_plan_marks_api_docs_as_not_deletable(self):
        src = "/**\n * Doc.\n */\nfunction f() {}\n"
        _, _, plan = self.build(src, "a.ts", opts=Options(shrink_docs=True))
        self.assertFalse(plan["items"][0]["deletable"])
        self.assertTrue(plan["items"][0]["is_api_doc"])

    def test_apply_plan_replaces_text(self):
        tmp, f, plan = self.build("// un commentaire verbeux\nconst a = 1;\n", "a.ts")
        plan["items"][0]["new_text"] = ["court"]
        edits, warns = planfile.to_edits(plan, tmp)
        doc = Document.load(f)
        self.assertEqual(apply_edits(doc.text, next(iter(edits.values()))), "// court\nconst a = 1;\n")
        self.assertEqual(warns, [])

    def test_empty_new_text_deletes(self):
        tmp, f, plan = self.build("// bruit\nconst a = 1;\n", "a.ts")
        plan["items"][0]["new_text"] = []
        edits, _ = planfile.to_edits(plan, tmp)
        self.assertEqual(apply_edits(Document.load(f).text, next(iter(edits.values()))), "const a = 1;\n")

    def test_null_new_text_leaves_untouched(self):
        tmp, f, plan = self.build("// bruit\nconst a = 1;\n", "a.ts")
        edits, _ = planfile.to_edits(plan, tmp)
        self.assertEqual(edits, {})

    def test_delimiters_from_the_model_are_stripped(self):
        tmp, f, plan = self.build("// bruit\nconst a = 1;\n", "a.ts")
        plan["items"][0]["new_text"] = ["// court */"]
        edits, warns = planfile.to_edits(plan, tmp)
        self.assertEqual(apply_edits(Document.load(f).text, next(iter(edits.values()))),
                         "// court\nconst a = 1;\n")
        self.assertTrue(any("délimiteur" in w for w in warns))

    def test_extra_lines_are_truncated(self):
        tmp, f, plan = self.build("// bruit\nconst a = 1;\n", "a.ts")
        plan["items"][0]["max_lines"] = 1
        plan["items"][0]["new_text"] = ["un", "deux", "trois"]
        edits, warns = planfile.to_edits(plan, tmp)
        self.assertEqual(apply_edits(Document.load(f).text, next(iter(edits.values()))),
                         "// un\nconst a = 1;\n")
        self.assertTrue(any("tronqué" in w for w in warns))

    def test_modified_file_is_refused(self):
        tmp, f, plan = self.build("// bruit\nconst a = 1;\n", "a.ts")
        plan["items"][0]["new_text"] = ["court"]
        f.write_text("// bruit\nconst a = 2;\n", encoding="utf-8")
        edits, warns = planfile.to_edits(plan, tmp)
        self.assertEqual(edits, {})
        self.assertTrue(any("modifié" in w for w in warns))

    def test_api_doc_cannot_be_deleted_through_a_plan(self):
        tmp, f, plan = self.build("/**\n * Doc.\n */\nfunction f() {}\n", "a.ts",
                                  opts=Options(shrink_docs=True))
        plan["items"][0]["new_text"] = []
        edits, warns = planfile.to_edits(plan, tmp)
        self.assertEqual(edits, {})
        self.assertTrue(any("suppression refusée" in w for w in warns))


class TestVerification(unittest.TestCase):
    def test_detects_a_stolen_line_of_code(self):
        before = "const a = 1;\nconst b = 2;\n"
        after = "const a = 1;\n"
        ok, why = verify_code_unchanged(before, after, L.JS)
        self.assertFalse(ok)
        self.assertIn("const b = 2", why)

    def test_accepts_comment_only_changes(self):
        before = "// long commentaire\nconst a = 1;\n"
        after = "// court\nconst a = 1;\n"
        self.assertTrue(verify_code_unchanged(before, after, L.JS)[0])


class TestBackup(unittest.TestCase):
    def setUp(self):
        from nukeai.guards import Backup

        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.a, self.b = self.tmp / "a.ts", self.tmp / "b.ts"
        self.a.write_text("un\n", encoding="utf-8")
        self.b.write_text("deux\n", encoding="utf-8")
        self.backup = Backup(self.tmp)
        self.backup.save(self.a)
        self.backup.save(self.b)
        self.addCleanup(shutil.rmtree, self.backup.slot, ignore_errors=True)
        self.a.write_text("MODIFIÉ\n", encoding="utf-8")
        self.b.write_text("MODIFIÉ\n", encoding="utf-8")

    def test_selective_rollback_touches_only_the_named_file(self):
        self.assertEqual(self.backup.rollback([self.a]), 1)
        self.assertEqual(self.a.read_text(), "un\n")
        self.assertEqual(self.b.read_text(), "MODIFIÉ\n")

    def test_full_rollback_restores_everything(self):
        self.assertEqual(self.backup.rollback(), 2)
        self.assertEqual(self.b.read_text(), "deux\n")


class TestCli(unittest.TestCase):
    def run_cli(self, *args, cwd=None):
        entry = Path(__file__).parent.parent / "scripts" / "nukeaicomment.py"
        return subprocess.run([sys.executable, str(entry), *args],
                              capture_output=True, text=True, cwd=cwd)

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        (self.tmp / "a.ts").write_text(
            "// Initialize the counter to zero\nlet counter = 0;\n", encoding="utf-8")
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def test_dry_run_does_not_write(self):
        before = (self.tmp / "a.ts").read_text()
        out = self.run_cli("nuke", "a.ts", "--no-color", cwd=self.tmp)
        self.assertEqual(out.returncode, 0)
        self.assertIn("simulation", out.stdout)
        self.assertEqual((self.tmp / "a.ts").read_text(), before)

    def test_apply_writes_and_backs_up(self):
        out = self.run_cli("nuke", "a.ts", "--apply", "--no-color", "-q", cwd=self.tmp)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertEqual((self.tmp / "a.ts").read_text(), "let counter = 0;\n")
        self.assertIn("sauvegarde", out.stdout)

    def test_restore_brings_the_file_back(self):
        self.run_cli("nuke", "a.ts", "--apply", "--no-color", "-q", cwd=self.tmp)
        out = self.run_cli("restore", "--no-color", cwd=self.tmp)
        self.assertEqual(out.returncode, 0, out.stdout)
        self.assertIn("Initialize the counter", (self.tmp / "a.ts").read_text())

    def test_scan_json_output(self):
        out = self.run_cli("scan", "a.ts", "--json", cwd=self.tmp)
        data = json.loads(out.stdout)
        self.assertEqual(data["stats"]["comments"], 1)

    def test_plan_then_apply(self):
        plan_path = self.tmp / "plan.json"
        out = self.run_cli("humanize", "a.ts", "-o", str(plan_path), "--no-color",
                           cwd=self.tmp)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        plan = json.loads(plan_path.read_text())
        plan["items"][0]["new_text"] = ["compteur remis à zéro à chaque cycle"]
        plan_path.write_text(json.dumps(plan), encoding="utf-8")
        out = self.run_cli("apply-plan", str(plan_path), "--apply", "--no-color", "-q",
                           cwd=self.tmp)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertIn("// compteur remis à zéro", (self.tmp / "a.ts").read_text())


if __name__ == "__main__":
    unittest.main()
