"""Protections (ce qu'on ne touche jamais) et détection du style « écrit par IA »."""

import re
from dataclasses import dataclass
from typing import List, Tuple

from .scanner import Comment

# --------------------------------------------------------------------------- #
# Protections
# --------------------------------------------------------------------------- #

DIRECTIVE_PATTERNS = [
    # JS / TS
    r"eslint-(?:disable|enable|env)", r"\beslint\s*\{", r"jshint\b", r"jslint\b",
    r"tslint:", r"stylelint-(?:disable|enable)", r"jscs:",
    r"@ts-\w+", r"@flow\b", r"\$FlowFixMe", r"@jsx\b",
    r"prettier-ignore", r"biome-ignore", r"dprint-ignore", r"rome-ignore",
    r"deno-lint-ignore", r"oxlint-disable", r"@formatter:(?:off|on)",
    r"webpack\w+:", r"@vite-ignore", r"vite-ignore",
    r"istanbul ignore", r"\bc8 ignore", r"\bv8 ignore", r"coverage:ignore",
    r"sourceMappingURL", r"sourceURL=",
    # Python
    r"\bnoqa\b", r"type:\s*ignore", r"pylint:", r"mypy:", r"pyright:", r"\bruff:",
    r"flake8:", r"isort:", r"fmt:\s*(?:on|off|skip)", r"yapf:", r"\bnosec\b",
    r"bandit:", r"pragma:\s*no\s*cover", r"noinspection",
    # C / C++ / C# / Java / Swift
    r"#\s*pragma\b", r"#\s*(?:region|endregion)\b", r"\bNOLINT",
    r"clang-format\s+(?:on|off)", r"checkstyle:", r"SuppressWarnings",
    r"@SuppressLint", r"sonar\.", r"NOSONAR",
    r"swiftlint:", r"@formatter",
    # Go
    r"go:(?:build|generate|embed|linkname|noinline|nosplit)", r"^\s*//\s*\+build",
    r"\bnolint\b",
    # Ruby / PHP
    r"rubocop:", r"frozen_string_literal:", r"typed:\s*\w+",
    r"phpcs:", r"@phpstan-", r"@psalm-", r"psalm-", r"codingStandardsIgnore",
    r"@codeCoverageIgnore",
    # Shell / infra / sécurité
    r"shellcheck\s+disable", r"hadolint\b", r"yamllint\b", r"gitleaks:allow",
    r"nosemgrep", r"trivy:ignore", r"tflint-ignore", r"checkov:skip",
    r"ansible-lint", r"kics-scan",
    # Éditeurs / fichiers générés
    r"vim:\s*set", r"-\*-\s*\w+", r"DO NOT EDIT", r"@generated\b", r"auto-?generated",
    r"Code generated by",
]
DIRECTIVE_RE = re.compile("|".join(DIRECTIVE_PATTERNS), re.I | re.M)

LICENSE_RE = re.compile(
    r"SPDX-License-Identifier|copyright|\(c\)\s*\d{4}|licen[cs]ed?\b|"
    r"all rights reserved|@license|@preserve|GNU General Public|MIT License|"
    r"Apache License",
    re.I,
)

MARKER_RE = re.compile(
    r"\b(TODO|FIXME|HACK|XXX|BUG|NOTE|OPTIMIZE|REVIEW|REFACTOR|DEPRECATED|WARNING|"
    r"IMPORTANT|CAUTION|SAFETY|SECURITY)\b"
)
MARKER_LOWER_RE = re.compile(r"\b(todo|fixme|hack|bug)\s*[:(\[]", re.I)

HEADER_ZONE_LINES = 8


@dataclass
class Protections:
    directives: bool = True
    headers: bool = True
    markers: bool = True
    docs: bool = True

    @classmethod
    def from_args(cls, args):
        return cls(
            directives=not getattr(args, "include_directives", False),
            headers=not getattr(args, "include_headers", False),
            markers=not getattr(args, "no_keep_todo", False),
            docs=not getattr(args, "include_docstrings", False),
        )


def protection_reason(c: Comment, prot: Protections) -> str:
    if prot.directives:
        if c.text.startswith("#!") and c.line == 1:
            return "shebang"
        if c.text.startswith("/*!"):
            return "directive (bloc préservé par les minifieurs)"
        if DIRECTIVE_RE.search(c.text):
            m = DIRECTIVE_RE.search(c.text)
            return f"directive outil ({m.group(0).strip()})"
    if prot.headers and c.line <= HEADER_ZONE_LINES and LICENSE_RE.search(c.text):
        return "en-tête licence/copyright"
    if prot.markers and (MARKER_RE.search(c.text) or MARKER_LOWER_RE.search(c.text)):
        m = MARKER_RE.search(c.text) or MARKER_LOWER_RE.search(c.text)
        return f"marqueur {m.group(1).upper()}"
    if prot.docs and (c.doc or c.kind == "docstring"):
        return "documentation d'API"
    return ""


def classify(comments: List[Comment], prot: Protections) -> List[Comment]:
    for c in comments:
        c.protected = protection_reason(c, prot) or None
        c.ai_score, c.ai_reasons = ai_score(c)
    return comments


# --------------------------------------------------------------------------- #
# Score « écrit par IA »
# --------------------------------------------------------------------------- #

AI_OPENERS = [
    (r"^this (?:function|method|class|component|hook|file|module|script|variable|"
     r"constant|interface|type|block|section|line|code)\b", 0.45, "ouverture « this … »"),
    (r"^(?:cette|ce|cet) (?:fonction|méthode|classe|composant|fichier|module|"
     r"variable|constante|section)\b", 0.45, "ouverture « cette … »"),
    (r"^(?:the )?(?:function|method|class) \w+ (?:does|is|returns|handles|takes)\b",
     0.4, "paraphrase de signature"),
    (r"^step \d+\s*[:.\-]", 0.4, "énumération « Step N »"),
    (r"^(?:first|next|then|finally|now)\s*,", 0.3, "connecteur de récit"),
    (r"^(?:d'abord|ensuite|puis|enfin)\s*,", 0.3, "connecteur de récit"),
    (r"^note that\b|^notez que\b|^il est important de\b|^il convient de\b",
     0.35, "formule d'accompagnement"),
    (r"^(?:here|we|let's|on va|nous allons)\b", 0.3, "narration"),
    (r"^(?:initialize|initializes|create|creates|return|returns|handle|handles|"
     r"set up|sets up|get|gets|update|updates|calculate|calculates|check|checks|"
     r"loop through|loops through|iterate|iterates) \b", 0.25, "reformulation d'action"),
    (r"\b(?:for example|in other words|essentially|basically|simply put|"
     r"autrement dit|c'est-à-dire|par exemple)\b", 0.25, "cheville rédactionnelle"),
    (r"\bensur(?:e|es|ing) that\b|\bmake sure to\b", 0.2, "tournure explicative"),
]
AI_OPENERS = [(re.compile(p, re.I), w, label) for p, w, label in AI_OPENERS]

BANNER_RE = re.compile(r"^[\s=*\-~_#/+]{6,}$")
SECTION_RE = re.compile(r"^[=\-*~_#]{2,}.*[=\-*~_#]{2,}$")
JSDOC_PARAM_RE = re.compile(r"@param\s+(?:\{[^}]*\}\s*)?\[?([\w.$]+)\]?\s*[-–—:]?\s*(.*)")
JSDOC_RETURN_RE = re.compile(r"@returns?\s+(?:\{[^}]*\}\s*)?(.*)")

STOPWORDS = {
    "the", "a", "an", "of", "to", "for", "and", "or", "is", "are", "be", "this",
    "that", "it", "in", "on", "with", "as", "by", "from", "we", "if", "then",
    "le", "la", "les", "un", "une", "de", "du", "des", "et", "ou", "est", "sont",
    "ce", "cette", "dans", "sur", "avec", "pour", "par", "si", "au", "aux", "en",
}


def _words(s: str):
    return [w for w in re.split(r"[^A-Za-zÀ-ſ]+", s.lower()) if w]


DIGIT_WORDS = {
    "0": ("zero", "zéro"), "1": ("one", "un"), "2": ("two", "deux"),
    "3": ("three", "trois"), "10": ("ten", "dix"), "100": ("hundred", "cent"),
}
OPERATOR_WORDS = [
    ("++", ("increment", "incrémente", "incremente")),
    ("--", ("decrement", "décrémente", "decremente")),
    ("+=", ("increment", "add", "adds", "sum", "incrémente", "ajoute")),
    ("-=", ("decrement", "subtract", "retire", "soustrait")),
]
KEYWORD_WORDS = {
    "if": ("check", "checks", "vérifie", "verifie", "test", "tests", "teste"),
    "for": ("loop", "loops", "iterate", "iterates", "each", "boucle", "parcourt"),
    "while": ("loop", "loops", "boucle"),
    "return": ("return", "returns", "retourne", "renvoie"),
    "true": ("enable", "enabled", "vrai", "active"),
    "false": ("disable", "disabled", "faux", "désactive"),
    "null": ("empty", "vide"), "none": ("empty", "vide"),
    "new": ("create", "creates", "crée", "cree", "instantiate"),
}


def _ident_words(code: str):
    """Vocabulaire du code : identifiants découpés, plus les mots qu'évoquent
    les littéraux et opérateurs — « increment » décrit `+=`, « zero » décrit `0`."""
    out = set()
    for tok in re.findall(r"[A-Za-z_$][\w$]*", code):
        for part in re.split(r"[_\s]+|(?<=[a-z0-9])(?=[A-Z])", tok):
            if part:
                low = part.lower()
                out.add(low)
                out.update(KEYWORD_WORDS.get(low, ()))
    for num in re.findall(r"\b\d+\b", code):
        out.update(DIGIT_WORDS.get(num, ()))
    for op, words in OPERATOR_WORDS:
        if op in code:
            out.update(words)
    return out


def _echoes(word: str, idents) -> bool:
    """Correspondance par préfixe, pour attraper item/items sans que « a » matche tout."""
    if word in idents:
        return True
    return any(len(i) >= 4 and (word.startswith(i) or i.startswith(word)) for i in idents)


def restates_code(c: Comment) -> float:
    """À quel point le commentaire ne fait que relire le code qu'il accompagne."""
    target = c.code_same_line if c.trailing else "\n".join(c.code_after.splitlines()[:2])
    if not target.strip():
        return 0.0
    words = [w for w in _words(c.inner) if w not in STOPWORDS and len(w) > 2]
    if len(words) < 2:
        return 0.0
    idents = _ident_words(target)
    return sum(1 for w in words if _echoes(w, idents)) / len(words)


def ai_score(c: Comment) -> Tuple[float, Tuple[str, ...]]:
    inner = c.inner.strip()
    score, reasons = 0.0, []

    if not inner:
        return 0.0, ()

    for rx, w, label in AI_OPENERS:
        if rx.search(inner):
            score += w
            reasons.append(label)
            break

    if any(BANNER_RE.match(l) or SECTION_RE.match(l) for l in c.inner_lines if l.strip()):
        score += 0.5
        reasons.append("bannière décorative")

    r = restates_code(c)
    if r >= 0.6:
        score += 0.5
        reasons.append(f"reformule le code voisin ({int(r * 100)}%)")
    elif r >= 0.4:
        score += 0.25
        reasons.append(f"proche du code voisin ({int(r * 100)}%)")

    echoes = _jsdoc_echo(c)
    if echoes:
        score += 0.3
        reasons.append(f"{echoes} tag(s) @param/@returns sans information")

    if c.n_lines >= 4 and c.kind != "docstring":
        score += 0.2
        reasons.append(f"bloc de {c.n_lines} lignes")

    if len(_words(inner)) > 25:
        score += 0.15
        reasons.append("verbeux")

    return min(score, 1.0), tuple(reasons)


def _jsdoc_echo(c: Comment) -> int:
    n = 0
    for line in c.inner_lines:
        m = JSDOC_PARAM_RE.search(line)
        if m:
            name, desc = m.group(1), m.group(2)
            if not desc.strip():
                n += 1
            else:
                dw = [w for w in _words(desc) if w not in STOPWORDS]
                nw = _ident_words(name)
                if dw and all(_echoes(w, nw) for w in dw):
                    n += 1
            continue
        m = JSDOC_RETURN_RE.search(line)
        if m and len(_words(m.group(1))) <= 3:
            n += 1
    return n
